services:
  db:
    build:
      context: ./infra/db
      dockerfile: ./Dockerfile
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    command: --require_secure_transport=OFF
  web:
    build:
      context: ./infra/web
      dockerfile: ./Dockerfile
    command: bash -c "rm -f /app/tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  bundle: